### ISSUE TITLE
Framerate drops with tree voxels 0541, 0544 and 0547 while using Polymost renderer

### ISSUE THREAD

**Issue by MCHDaniel** [fgsfds/Blood-Voxel-Pack#44]
Whenever one of these voxels (especially 0541 and 0544) is present on the map, the game stutters a lot. Tested with NBlood. Doesn't happen with the classic renderer.

**Comment by Dzierzan** [comment]
Nothing we can do. Those are highly complicated voxels. It might work better in classic renderer because render method of voxels is different in classic:

Classic - voxels are rendered as flat surfaces, take a look at close range.
Polymost - voxels are converted to meshes. That's a lot of polygon to handle and Build engine doesn't do here a good job.

If it lags for you, just comment them out in def script.
